### ISSUE TITLE
Upgrade ruby version to 2.5.1

### ISSUE THREAD

**Issue by deivid-rodriguez** [podemos-info/participa2#29]
This needs some coordination for deployment (right?). But it'd be nice to get this up to date for speed, security and all that stuff :)

**Comment by deivid-rodriguez** [comment]
Updated this issue's title so we go directly to 2.5.1 :)

**Comment by leio10** [comment]
Fixed in https://github.com/podemos-info/participa2/commit/848ffff9713de6a01d5c7c3148d9cb44aff9a8f2
